before_script:
  # load the requested modules on oberon
  - module load python-anaconda

shennong-build:
  stage: build
  script:
    - conda activate shennong-ci
    - python setup.py install

shennong-test:
  stage: test
  script:
    - conda activate shennong-ci
    - python setup.py test

# documentation is available on https://coml.lscp.ens.fr/shennong
shennong-doc:
  stage: deploy
  script:
    - conda activate shennong-ci
    - sphinx-build doc doc/build
    - scp -r doc/build/* coml.lscp.ens.fr:/var/www/html/shennong

# shennong package is available on oberon with "source activate shennong"
shennong-deploy:
  stage: deploy
  script:
    - source activate shennong
    - cd /cm/shared/apps/shennong
    - git pull origin master
    - python setup.py install
    - python setup.py test
