# test on linux
shennong-linux:
  stage: test
  script:
    - module load anaconda/3
    - conda activate shennong-ci
    - conda env update -n shennong-ci -f environment.yml
    - python setup.py install
    - python setup.py test

# test on macos
shennong-osx:
  tags:
    - macos
  stage: test
  script:
    - conda activate shennong
    - sed '/pykaldi/d' environment.yml > environment.macos.yml
    - conda env update -n shennong -f environment.macos.yml
    - rm -f environment.macos.yml
    - python setup.py install
    - python setup.py test

# documentation is available on https://coml.lscp.ens.fr/shennong
shennong-doc:
  stage: deploy
  only:
    refs:
      - master
  script:
    - module load anaconda/3
    - module load texlive/2018
    - conda activate shennong-ci
    - sphinx-build doc/source doc/build
    - scp -r doc/build/* coml.lscp.ens.fr:/var/www/html/shennong

# shennong package is available on oberon with "conda activate shennong"
shennong-deploy:
  stage: deploy
  only:
    refs:
      - master
  script:
    - module load anaconda/3
    - cd /shared/apps/shennong
    - git pull origin master
    - conda env update -n shennong -f environment.yml
    - conda activate shennong
    - python setup.py install
    - python setup.py test
