before_script:
  # load the requested modules on oberon
  - module load anaconda/3

shennong-build:
  stage: build
  script:
    - conda activate shennong-ci
    - conda env update -n shennong-ci -f environment.yml
    - python setup.py install

shennong-test:
  stage: test
  script:
    - conda activate shennong-ci
    - python setup.py test

# documentation is available on https://coml.lscp.ens.fr/shennong
shennong-doc:
  stage: deploy
  only:
    refs:
      - master
  script:
    - conda activate shennong-ci
    - sphinx-build doc/source doc/build
    - scp -r doc/build/* coml.lscp.ens.fr:/var/www/html/shennong

# shennong package is available on oberon with "conda activate shennong"
shennong-deploy:
  stage: deploy
  only:
    refs:
      - master
  script:
    - conda activate shennong
    - cd /shared/apps/shennong
    - git pull origin master
    - conda env update -n shennong -f environment.yml
    - python setup.py install
    - python setup.py test
