name: shennong
channels:
  - pykaldi
  - conda-forge
dependencies:
  - python=3.7
  - cython
  - flake8
  - h5py
  - ipython
  - joblib
  - numpy
  - pykaldi
  - pyparsing
  - pytest
  - pytest-cov
  - pytest-runner
  - pyyaml
  - scipy
  - sox  # sox binary
  - sphinx
  - sphinx_rtd_theme
  - tabulate
  - pip:
      - h5features
      - json-tricks
      - ninja
      - sox  # sox python wrapper
